Repository AngelinaBz/train-a, pull requests merged in 2024-09, with the labels that each got.

#33 Order page for Admin
  train-a/package-lock.json
  train-a/src/app/app.component.html
  train-a/src/app/app.component.ts
  train-a/src/app/app.routes.ts
  train-a/src/app/orders/components/cancel-dialog/cancel-dialog.component.html
  train-a/src/app/orders/components/cancel-dialog/cancel-dialog.component.scss
  train-a/src/app/orders/components/cancel-dialog/cancel-dialog.component.spec.ts
  train-a/src/app/orders/components/cancel-dialog/cancel-dialog.component.ts
  train-a/src/app/orders/components/order-card/order-card.component.html
  train-a/src/app/orders/components/order-card/order-card.component.scss
  train-a/src/app/orders/components/order-card/order-card.component.ts
  train-a/src/app/orders/models/order.model.ts
  train-a/src/app/orders/pages/orders-page/orders-page.component.html
  train-a/src/app/orders/pages/orders-page/orders-page.component.scss
  train-a/src/app/orders/pages/orders-page/orders-page.component.spec.ts
  train-a/src/app/orders/pages/orders-page/orders-page.component.ts
  train-a/src/app/orders/pages/orders-page/orders.component.html
  train-a/src/app/orders/pages/orders-page/orders.component.scss
  train-a/src/app/orders/pages/orders-page/orders.component.spec.ts
  train-a/src/app/orders/pages/orders-page/orders.component.ts
  train-a/src/app/orders/pages/orders.component.html
  train-a/src/app/orders/pages/orders.component.scss
  train-a/src/app/orders/state/order.actions.ts
  train-a/src/app/orders/state/order.effects.ts
  train-a/src/app/orders/state/order.reducers.ts
  train-a/src/app/shared/services/api.service.ts
  train-a/src/app/user/models/UserWithId.ts
  train-a/src/app/user/state/user.actions.ts
  train-a/src/app/user/state/user.effects.ts
  train-a/src/app/user/state/user.facade.ts
  train-a/src/app/user/state/user.reducers.ts
  train-a/src/app/user/state/user.selectors.ts
  train-a/src/styles.scss
Labels: enhancement

#36 Routes page
  train-a/src/app/app.config.ts
  train-a/src/app/app.routes.ts
  train-a/src/app/orders/components/order-card/order-card.component.scss
  train-a/src/app/routes/components/delete-route-dialog/delete-route-dialog.component.html
  train-a/src/app/routes/components/delete-route-dialog/delete-route-dialog.component.scss
  train-a/src/app/routes/components/delete-route-dialog/delete-route-dialog.component.spec.ts
  train-a/src/app/routes/components/delete-route-dialog/delete-route-dialog.component.ts
  train-a/src/app/routes/components/route-card/route-card.component.html
  train-a/src/app/routes/components/route-card/route-card.component.scss
  train-a/src/app/routes/components/route-card/route-card.component.spec.ts
  train-a/src/app/routes/components/route-card/route-card.component.ts
  train-a/src/app/routes/models/route.model.ts
  train-a/src/app/routes/pages/routes-admin-page/routes-admin-page.component.html
  train-a/src/app/routes/pages/routes-admin-page/routes-admin-page.component.scss
  train-a/src/app/routes/pages/routes-admin-page/routes-admin-page.component.spec.ts
  train-a/src/app/routes/pages/routes-admin-page/routes-admin-page.component.ts
  train-a/src/app/routes/state/routes.actions.ts
  train-a/src/app/routes/state/routes.effects.ts
  train-a/src/app/routes/state/routes.facade.ts
  train-a/src/app/routes/state/routes.reducers.ts
  train-a/src/app/routes/state/routes.selectors.ts
  train-a/src/styles.scss
Labels: enhancement

#40 Fix validation and responsive design
  train-a/src/app/auth/components/signup-form/signup-form.component.html
  train-a/src/app/orders/components/cancel-dialog/cancel-dialog.component.html
  train-a/src/app/routes/pages/routes-admin-page/routes-admin-page.component.scss
Labels: bug

#39 Update readme fix cross check issue
  README.md
  train-a/README.md
  train-a/src/app/app.config.ts
  train-a/src/app/app.routes.ts
  train-a/src/app/auth/interceptor/auth.interceptor.ts
  train-a/src/app/carriages/components/carriage-card/carriage-card.component.scss
  train-a/src/app/search/pages/details-page/details-page.component.html
  train-a/src/app/search/pages/details-page/details-page.component.scss
  train-a/src/app/search/pages/details-page/details-page.component.ts
  train-a/src/assets/android-chrome-192x192.png
  train-a/src/assets/android-chrome-512x512.png
  train-a/src/assets/apple-touch-icon.png
  train-a/src/assets/favicon-16x16.png
  train-a/src/assets/favicon-32x32.png
  train-a/src/assets/favicon.ico
  train-a/src/assets/site.webmanifest
  train-a/src/index.html
Labels: documentation, enhancement
